# SPDX-FileCopyrightText: 2025 Jack Henry
#
# SPDX-License-Identifier: Apache-2.0

name: Design Issue
description: Report a design issue
title: '[Design Issue]: '
labels: 'status: needs triage, type: figma design kit'
type: figma design kit
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a design issue regarding our web components or Figma UI Kit. Please remember to search for open and closed issues before submitting.

        Jack Henry teams seeking support should report issues through our internal Slack channel.
  - type: dropdown
    id: affected-package
    attributes:
      label: Affected Package
      description: Which package are you experiencing the design issue in?
      options:
        - '@jack-henry/jh-elements' 
        - '@jack-henry/jh-tokens'
        - '@jack-henry/jh-icons'
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: Please specify the version of the package you are using. e.g., "1.14.0"
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description of the Issue
      description: | 
        Provide details about the design issue you are reporting and whether this an issue specific to the design of a component or the designer experience of a Figma component.
    validations:
      required: true
