name: Bug Report
about: Report something that is not working as expected.
title: '[Bug]: '
labels: 'type: bug, status: needs triage'
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug in the Jack Henry Design System! Please remember to search for open issues before submitting a new issue.
  - type: dropdown
    id: affected-browser
    attributes:
      label: Affected Browsers
      description: Which browser(s) are you experiencing the issue? 
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
    validations:
      required: true
  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: Please specify the version of the browser you are using. e.g., "90.0.4430.93"
    validations:
      required: true
  - type: input
    id: affected-package
    attributes:
      label: Affected Package
      description: Which package and version of the Jack Henry Design System are you experiencing the issue in? e.g., "@jack-henry/jh-ui v1.14.0"
      validations:
        required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Please provide a detailed description of the bug you are experiencing.
    validations:
      required: true
  - type: textarea
    id: reproduce-issue
    attributes:
      label: How to Reproduce the Issue
      description: Please provide detailed steps on how to reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please describe what you expected to happen instead.
    validations:
      required: true
  
