name: "Install dependencies"
description: "Setup and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 8.5.1

    - name: Install Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Output .npmrc
      shell: bash
      run: |
        echo "registry=https://registry.npmjs.org/" > ~/.npmrc
        echo "include-workspace-root: true" >> ~/.npmrc
      
    - name: Install dependencies
      shell: bash
      run: pnpm install:all