name: Release
on:
  push:
    branches: [main] # Adjust branch name as needed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}  
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: read
      pull-requests: write
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags - Needed for Changsets to generate changelogs with commit
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Publish all packages
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm -r publish --registry https://registry.npmjs.org/

      - name: Create GitHub Release
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          createGithubReleases: true